# 以下内容生成docker镜像

# 基础镜像
FROM golang:latest

# 容器环境变量设置，会覆盖默认的变量值
ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE="on"

# 工作区
WORKDIR /go/src/app

# 复制仓库源文件到容器里
COPY . .

# 编译可执行二进制文件
RUN go build -o webserver

# 容器向外提供服务的暴露端口
EXPOSE 80

# 启动服务
ENTRYPOINT ["./webserver"]